version: "3.8"

services:
  redis:
      image: redis:alpine
      container_name: redis
      networks:
        - dev
      ports:
        - "6379:6379" 

  backend:
    build:
      context: ./core
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    env_file:
      - ./core/.env
    depends_on:
      - redis
    volumes:
      - './db:/db'
    ports:
      - "8000:8000"
    networks:
        - dev

  nginx:
    image: nginx:stable-alpine
    ports: 
      - "80:80"
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    depends_on:
      - backend 
    networks:
      - dev

  telegram_bot:
    build:
      context: ./telegram_bot
      dockerfile: Dockerfile
    container_name: telegram_bot
    restart: always
    env_file:
      - ./telegram_bot/.env
    depends_on:
      - backend
    networks:
        - dev


networks:
  dev:
