# Generated by Django 5.1.7 on 2025-03-20 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'клиент', 'verbose_name_plural': 'Клиенты'},
        ),
        migrations.AlterModelOptions(
            name='clientcalculation',
            options={'verbose_name': 'расчёт', 'verbose_name_plural': 'расчёты'},
        ),
        migrations.AlterModelOptions(
            name='clientstatus',
            options={'verbose_name': 'статус клиента', 'verbose_name_plural': 'Статусы клиентов'},
        ),
    ]
