# Generated by Django 5.1.7 on 2025-03-25 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_feedbackrequest_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcalculation',
            name='age',
            field=models.CharField(default='', max_length=20, verbose_name='Возраст'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcalculation',
            name='currency',
            field=models.CharField(default='', max_length=3, verbose_name='Валюта'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcalculation',
            name='engine_type',
            field=models.CharField(default='', max_length=50, verbose_name='Тип двигателя'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcalculation',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcalculation',
            name='volume',
            field=models.FloatField(default=0, verbose_name='Объём двигателя'),
            preserve_default=False,
        ),
    ]
