# Generated by Django 5.1.7 on 2025-03-25 00:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_clientcalculation_age_clientcalculation_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcalculation',
            name='client',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.client', verbose_name='Клиент'),
            preserve_default=False,
        ),
    ]
