# Generated by Django 5.1.7 on 2025-03-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clientcalculation_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientcalculation',
            name='car_type',
            field=models.CharField(default='', max_length=50, verbose_name='Тип транспортного средства'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientcalculation',
            name='power_kw',
            field=models.CharField(default='', max_length=10, verbose_name='Мощность (кВт, за 30 мин)'),
            preserve_default=False,
        ),
    ]
