# Generated by Django 5.1.7 on 2025-03-28 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_clientcalculation_power_kw'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculationStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'статус расчёта',
                'verbose_name_plural': 'статусы расчётов',
            },
        ),
        migrations.AddField(
            model_name='clientcalculation',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.calculationstatus', verbose_name='Статус'),
        ),
    ]
