# Generated by Django 5.1.7 on 2025-03-28 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_calculationstatus_clientcalculation_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientcalculation',
            name='price',
        ),
    ]
