# Generated by Django 5.1.7 on 2025-03-28 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_clientcalculation_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя в Telegram'),
        ),
    ]
