# Generated by Django 5.1.7 on 2025-03-20 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('currencies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='currency',
            name='name',
            field=models.CharField(default='', max_length=50, verbose_name='Название'),
            preserve_default=False,
        ),
    ]
